apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - nodePort: 32000  # Port exposed outside the cluster
      port: 9000       # Internal service port
      targetPort: 5678 # Pod port
  selector:
    app: myapp
